Upgraded spring boot dependency to 2.6.4 #1057
mercedes-benz/sechub pull request #1080
Opened 2022-02-28 08:47 UTC by de-jcup

This PR 
- closes #1057 1057

2022-02-28 10:06 UTC, Jeeppler requested changes
It is not enough to just upgrade the SpringBoot version. SpringBoot 2.6.4 upgraded a number of packages: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.4. Some of the packages like `slf4j` are explicitly mentioned in `libraries.gradle`. The problem is, we have to upgrade the dependencies in `libraries.gradle` manually, otherwise we include the same dependencies multiple times.

2022-03-08 17:40 UTC, Jeeppler approved these changes
Looks good. However, I found one odd dependency: spring boot starter mongodb. Why do we need that?

2022-03-08 17:40 UTC, Jeeppler commented on libraries.gradle
> +        springboot_starter_data_mongodb:       "org.springframework.boot:spring-boot-starter-data-mongodb",
Why do we need the MongoDB dependency?

2022-03-09 08:45 UTC, de-jcup commented on libraries.gradle
> +        springboot_starter_data_mongodb:       "org.springframework.boot:spring-boot-starter-data-mongodb",
We do not need this - will be removed.

2022-03-09 09:18 UTC, merged