Fixes PDS shutdown problem #998
mercedes-benz/sechub pull request #1360
Opened 2022-06-02 06:28 UTC by de-jcup

This PR
- closes #998

2022-06-02 07:42 UTC, sven-dmlr requested changes
I've tested the behavior:

After `./gradlew startIntegrationTestPDS` and following `./gradlew stopIntegrationTestPDS` the process is gone. :heavy_check_mark: 

But: After `./gradlew integrationtest` has finished, still the PDS process is running.
And it cannot be stopped with `./gradlew stopIntegrationTestPDS`.
Only a `kill <process id>` stops the PDS.
Please check how this can be fixed.

2022-06-03 17:41 UTC, de-jcup commented
It is very strange, but this happens also at my machine when starting the complete integration tests via scripts + gradle.
Finally, in the last commit, I did a hard System.exit(0) at the end. This is only for integration tests, so it is okay (I normally would NOT do this in normal production code - but her it is okay). I kept the former introduced preDestroy hook because it works outside integration test scripts very well.

2022-06-07 08:44 UTC, sven-dmlr approved these changes
Looks good now and works as expected. :+1: 

Please consider the proposed wording change.
(Anyway I have approved the PR, because there's no major finding)

2022-06-07 08:44 UTC, sven-dmlr commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/IntegrationTestPDSRestController.java
> +        LOG.info("Integration test server shutdown wished...");
Suggest to use a more common wording:
```suggestion
        LOG.info("Integration test server shutdown requested...");
```

2022-06-08 14:23 UTC, merged