Set content length for S3 client #1471
mercedes-benz/sechub pull request #1508
Opened 2022-07-26 10:42 UTC by Jeeppler

- implemented set content length for job storage and s3 job storage
- added/extended unit tests

2022-08-10 10:42 UTC, de-jcup requested changes
Good job, but I want some changes  - please read the comments

2022-08-10 10:42 UTC, de-jcup commented on sechub-testframework/src/main/java/com/mercedesbenz/sechub/test/TestUtil.java
> +     * @return filePath
Please change back to "file" - Path is the java.nio representation of an file or folder..

2022-08-19 08:40 UTC, winzj requested changes
Good job, looks good to me. I have some minor suggestions, please have a look at my comments.

2022-08-22 08:07 UTC, Jeeppler commented on sechub-integrationtest/src/main/java/com/mercedesbenz/sechub/integrationtest/internal/TestRestHelper.java
> +        headers.set("", checkSum);
I do not know, that was not my design decision.

@de-jcup can probably answer this question.

2022-08-24 07:39 UTC, winzj requested changes
Looks good, just found a small typo in a byte size definition. Please, see comment below.

2022-08-24 07:39 UTC, winzj commented on sechub-storage-s3-aws/src/main/java/com/mercedesbenz/sechub/storage/s3/AwsS3TransferManagerFactory.java
> +        long multipartUploadThreshold = 5 * 1024 * 1025; // threshold 5 MiB
I think there is a typo in this line.
```suggestion
        long multipartUploadThreshold = 5 * 1024 * 1024; // threshold 5 MiB
```

2022-08-25 07:11 UTC, winzj approved these changes
Looks good.

2022-08-25 07:23 UTC, merged