Disable password encode in PDS. Remove {noop} from profiles. #673
mercedes-benz/sechub pull request #1671
Opened 2022-09-29 07:16 UTC by zigfridus

Disable password encode in PDS. 
Remove {noop} from profiles. 
Closes #673

2022-09-29 07:21 UTC, zigfridus commented
@Jeeppler 
Please review this PR.

2022-09-29 12:35 UTC, Jeeppler commented
@de-jcup I assigned you as reviewer.

2022-09-29 14:40 UTC, de-jcup requested changes
There are some changes necessary. Please read my comments.

2022-09-29 14:40 UTC, de-jcup commented on sechub-pds/src/main/resources/application-pds_integrationtest.yml
> -       apitoken: "{noop}pds-inttest-apitoken"
This is fine, so we test the new "add noop when missing" mechanism automatically when integration tests are executed by GitHub actions.

2022-09-29 14:40 UTC, de-jcup commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/security/PDSSecurityConfiguration.java
> +        techUserApiToken = null;
Just a reminder: Please do always execute `./gradlew spotlessApply` to automatically format source code before you push to Git.

2022-09-30 11:08 UTC, zigfridus commented
Hello @de-jcup 
I changed my PR according to your comments. 
Please have a look.

2022-10-11 14:23 UTC, de-jcup commented on sechub-pds/src/test/java/com/mercedesbenz/sechub/pds/security/PDSPasswordTransformerTest.java
> +}
After adding the null argument check implementaiton, please add a junit5 test method like this:

```suggestion
  @Test
  void null_argument() {
     /* execute + test */
     assertThrows(IllegalArgumentException.class, () -> {
         transformerToTest.transformPassword(null);
     });
  }
}
```

2022-10-13 12:12 UTC, zigfridus commented
@de-jcup
I made changes in my code according to your comments.
Please have a look.

2022-10-13 12:33 UTC, de-jcup approved these changes
Good job :rocket: 
Thank you for the contribution.

2022-10-13 12:33 UTC, merged