Feature 1578 upgrade scancode
mercedes-benz/sechub pull request #1727
Opened 2022-11-03 17:28 UTC by Jeeppler

- Upgrade scancode
- Use PDS base image
- Introduce message script
- Use messages for diagnostics
- Overwrite `pool.py` (ugly hack; see: https://github.com/nexB/scancode-toolkit/issues/2908)

closes: #1578

2022-11-04 17:03 UTC, sven-dmlr requested changes
Looks overall good. :+1: 

Please check the comments.

2022-11-04 18:04 UTC, Jeeppler commented on sechub-pds-solutions/scancode/docker/scripts/scancode.sh
> +    mv "$diagnostics_file" "${PDS_JOB_USER_MESSAGES_FOLDER}/INFO_message_$(date +%Y-%m-%d_%H.%M.%S_%N).txt"
You are spot, on the file is huge.

2022-11-04 18:05 UTC, Jeeppler commented on sechub-pds-solutions/scancode/docker/scripts/scancode_mock.sh
> +    cat "$MOCK_FOLDER/scancode_mock.json" > "${PDS_JOB_USER_MESSAGES_FOLDER}/INFO_message_$(date +%Y-%m-%d_%H.%M.%S_%N).txt"
Same reason, the file is very large.

2022-11-07 16:15 UTC, Jeeppler commented on sechub-pds-solutions/scancode/test/pds-job-config.json
> +            "value": "{\n  \"data\" : {\n    \"sources\" : [ ],\n    \"binaries\" : [ {\n      \"fileSystem\" : {\n        \"files\" : [ \"Armbian_22.08.1_Jetson-nano_jammy_current_5.18.19.img\" ],\n
I will keep this for now. This is output generated by the PDS-Tool.

2022-11-07 16:23 UTC, Jeeppler commented on sechub-pds-solutions/scancode/docker/scripts/message.sh
> +# TODO: this script can be moved to the PDS base image
Done.

2022-11-08 11:56 UTC, sven-dmlr approved these changes

2022-11-08 15:38 UTC, merged