Implemented simple resilience PDS storage read #1805
mercedes-benz/sechub pull request #1819
Opened 2022-12-14 08:56 UTC by de-jcup

This PR
- closes #1805

2022-12-14 12:53 UTC, Jeeppler requested changes
Tests and logic look good 🥇 

I only found smaller issues. Have a look at the comments.

2022-12-14 12:53 UTC, Jeeppler commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/util/PDSResilientRetryExecutor.java
> +            thrower.throwException("Even after " + attempts + " attempts it was not possible to execute '" + identifier + "' ! Will throw last cause.",
```suggestion
            thrower.throwException("Even after " + attempts + " attempts it was not possible to execute '" + identifier + "'! Will throw last cause.",
```

2022-12-14 15:21 UTC, de-jcup commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/util/PDSResilientRetryExecutor.java
> +                    LOG.info("The execution of '{}' was succesful", retryNumber, identifier);
- The retry number parameter must be removed
- identifier can be anything and shall give a hint whats going on here. The mechanism of using the identifier inside the log messages to explain the context is used everywhere.

I would remove the number but keep the identifier.

2022-12-15 08:19 UTC, Jeeppler commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/util/PDSResilientRetryExecutor.java
> +                    LOG.info("The execution of '{}' was succesful", retryNumber, identifier);
That makes sense.

2022-12-15 08:26 UTC, Jeeppler approved these changes
Looks good.

2022-12-16 08:25 UTC, merged