Made many s3 client options configurable via spring values #1871
mercedes-benz/sechub pull request #1872
Opened 2023-01-18 17:25 UTC by de-jcup

This PR
- closes 1871

2023-01-24 17:30 UTC, sven-dmlr requested changes
Looks good :+1: 

* Please check my comments about the documentation texts.

* It seems that `sharedkernel/storage/S3PropertiesSetup.java` and `pds/storage/PDSS3PropertiesSetup.java` are redundant. Are there good reasons for this?

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
> +    @PDSMustBeDocumented(value = "S3 client timeout for creating new connections.", scope = "storage")
```suggestion
    @PDSMustBeDocumented(value = "S3 client timeout (in milliseconds) for creating new connections.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
> +    @PDSMustBeDocumented(value = "S3 client timeout for a request. 0 means it is disabled.", scope = "storage")
```suggestion
    @PDSMustBeDocumented(value = "S3 client timeout (in milliseconds) for a request. 0 means it is disabled.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
> +    @PDSMustBeDocumented(value = "S3 client timeout for execution. 0 means it is disabled.", scope = "storage")
```suggestion
    @PDSMustBeDocumented(value = "S3 client timeout (in milliseconds) for execution. 0 means it is disabled.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
> +    @PDSMustBeDocumented(value = "S3 client time a connection can be idle in the connection pool before it must be validated that it's still open.", scope = "storage")
```suggestion
    @PDSMustBeDocumented(value = "S3 client time (in milliseconds) a connection can be idle in the connection pool before it must be validated that it's still open.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
> +    @PDSMustBeDocumented(value = "S3 client time a connection can be idle in the connection pool before it must be validated that it's still open.", scope = "storage")
The text is copied from line 62. Please fix.

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/storage/PDSS3PropertiesSetup.java
> +    @PDSMustBeDocumented(value = "S3 client timeout in milliseconds for reading from a connected socket.", scope = "storage")
```suggestion
    @PDSMustBeDocumented(value = "S3 client timeout (in milliseconds) for reading from a connected socket.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/S3PropertiesSetup.java
> +    @MustBeDocumented(value = "S3 client timeout for creating new connections.", scope = "storage")
```suggestion
    @MustBeDocumented(value = "S3 client timeout (in milliseconds) for creating new connections.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/S3PropertiesSetup.java
> +    @MustBeDocumented(value = "S3 client timeout in milliseconds for reading from a connected socket.", scope = "storage")
```suggestion
    @MustBeDocumented(value = "S3 client timeout (in milliseconds) for reading from a connected socket.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/S3PropertiesSetup.java
> +    @MustBeDocumented(value = "S3 client timeout for a request. 0 means it is disabled.", scope = "storage")
```suggestion
    @MustBeDocumented(value = "S3 client timeout (in milliseconds) for a request. 0 means it is disabled.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/S3PropertiesSetup.java
> +    @MustBeDocumented(value = "S3 client timeout for execution. 0 means it is disabled.", scope = "storage")
```suggestion
    @MustBeDocumented(value = "S3 client timeout (in milliseconds) for execution. 0 means it is disabled.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/S3PropertiesSetup.java
> +    @MustBeDocumented(value = "S3 client time a connection can be idle in the connection pool before it must be validated that it's still open.", scope = "storage")
```suggestion
    @MustBeDocumented(value = "S3 client time (in milliseconds) a connection can be idle in the connection pool before it must be validated that it's still open.", scope = "storage")
```

2023-01-24 17:30 UTC, sven-dmlr commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/storage/S3PropertiesSetup.java
> +    @MustBeDocumented(value = "S3 client time a connection can be idle in the connection pool before it must be validated that it's still open.", scope = "storage")
The text is copied from line 62. Please fix.

2023-02-06 07:24 UTC, de-jcup commented
> Looks good +1
> 
>     * Please check my comments about the documentation texts.
> 
>     * It seems that `sharedkernel/storage/S3PropertiesSetup.java` and `pds/storage/PDSS3PropertiesSetup.java` are redundant. Are there good reasons for this?

I changed the documentation parts with last commit

About the redundancy ... yes it is very similar, but we need this 
- we have different keys for the values (e.g. "sechub.pds.storage... " versus "sechub.storage...."
- PDS and SecHub are different products which do not communicate directly or share a domain etc. The only shared 
  parts inside the "common-*" libraries which have no dependency to spring/spring boot but we need spring values to 
  inject, so it cannot be shared.

2023-02-06 08:50 UTC, sven-dmlr approved these changes

2023-02-06 10:21 UTC, merged