Dockerfiles for Fedora, Ubuntu and Rocky #1535, #1537, #1538
mercedes-benz/sechub pull request #1980
Opened 2023-02-21 14:59 UTC by Jeeppler

- added the ability to change the ports #1965
- Start scripts for Ubuntu (otherwise same as Debian) #1537
- Dockerfile and Java installer scripts for RockyLinux #1538
- Dockerfile and Java installer scripts for Fedora #1535

closes: #1535
closes: #1537
closes: #1538

2023-02-21 15:00 UTC, Jeeppler commented
Still waiting for adoptium/installer/issues/611 to be fixed.

2023-02-24 09:48 UTC, sven-dmlr requested changes
Good job.

Found some minor things.
Please check my comments.

2023-02-24 09:48 UTC, sven-dmlr commented on sechub-solution/docker/SecHub-Fedora.dockerfile
> +ARG TARGETARCH
Good to know :+1:

2023-02-24 09:48 UTC, sven-dmlr commented on sechub-solution/docker/SecHub-Fedora.dockerfile
> +ARG GO="go1.20.1.linux-${TARGETARCH}.tar.gz"
This argument is never used. You install the distribution's Golang package.
```suggestion
```

2023-02-24 09:48 UTC, sven-dmlr commented on sechub-solution/docker/SecHub-Fedora.dockerfile
> +ARG GO
```suggestion
```

2023-02-24 09:48 UTC, sven-dmlr commented on sechub-solution/docker/install-java/fedora/install-java.sh
> +if [ -z "$JAVA_RUNTIME" ]
If the possible values are jre and jdk, you could check this
```suggestion
if [ "$JAVA_RUNTIME" != "jdk" && "$JAVA_RUNTIME" != "jre" ]
```

2023-02-24 09:48 UTC, sven-dmlr commented on sechub-solution/docker/install-java/rocky/install-java.sh
> +if [ -z "$JAVA_RUNTIME" ]
```suggestion
if [ "$JAVA_RUNTIME" != "jdk" && "$JAVA_RUNTIME" != "jre" ]
```

2023-02-24 15:45 UTC, sven-dmlr approved these changes

2023-02-24 22:06 UTC, merged