Fix SPDX Tool bug in Scancode #2072
mercedes-benz/sechub pull request #2088
Opened 2023-03-16 16:51 UTC by Jeeppler

- Made SPDX Tool configurable
- Added checks to ensure the SPDX Tool is installed and called proberly
- Added script to generate test files

closes: #2072

2023-03-17 16:49 UTC, sven-dmlr requested changes
Looks good, but some things don't work.
Please check my comments/suggestions.

Also creating an extra checksums file in `Scancode-Debian.dockerfile` is not necessary.
You could replace lines 52-54 with:
```dockerfile
echo "$SPDX_TOOL_CHECKSUM" | sha256sum -c
```
(see also my comment in 10-create-image.sh regarding blanks in build args)

2023-03-17 16:49 UTC, sven-dmlr commented on sechub-pds-solutions/scancode/10-create-image.sh
> +- SCANCODE_VERSION - Scancode version to use. E.g. 31.2.4
Is `SCANCODE_VERSION` mandatory or optional?
I think it's mandatory and should be checked in this script.

Please also document here `SPDX_TOOL_VERSION` and `SPDX_TOOL_CHECKSUM`
Where can I find out the version and the checksum and how is the expected formatting?

2023-03-17 16:49 UTC, sven-dmlr commented on sechub-pds-solutions/scancode/10-create-image.sh
> +if [[ ! -z "$SPDX_TOOL_VERSION" ]] ; then
If `SPDX_TOOL_VERSION` and `SPDX_TOOL_CHECKSUM` are unset, the Docker image build fails now.

Also blanks inside a Docker build argument (SPDX_TOOL_CHECKSUM) did not work for me:
```
> export SPDX_TOOL_VERSION="1.1.5"
> export SPDX_TOOL_CHECKSUM="feff2d5e7f66576a6e411d65a18046dbaf7ed6bad6e223a1c0ecee075a72b70b  tools-java-1.1.5-jar-with-dependencies.jar"
> export SCANCODE_VERSION=31.2.4
> ./10-create-image.sh my.registry/sechub/pds-scancode-test 0.999.0 my.registry/sechub/pds_base_image:latest
>> Base image: my.registry/sechub/pds_base_image:latest
>> Scancode version: 31.2.4
>> SPDX Tool version: 1.1.5
>> SPDX Tool checksum: feff2d5e7f66576a6e411d65a18046dbaf7ed6bad6e223a1c0ecee075a72b70b  tools-java-1.1.5-jar-with-dependencies.jar
"docker build" requires exactly 1 argument.
See 'docker build --help'.
...
```

As a solution, we could set `SPDX_TOOL_CHECKSUM="feff2d5e7f66576a6e411d65a18046dbaf7ed6bad6e223a1c0ecee075a72b70b"`
and the check in the Dockerfile (replace lines 52-54) like this:
```Dockerfile
echo "${SPDX_TOOL_CHECKSUM} tools-java-${SPDX_TOOL_VERSION}-jar-with-dependencies.jar" | sha256sum -c
```

2023-03-17 17:57 UTC, Jeeppler commented on sechub-pds-solutions/scancode/docker/scripts/scancode.sh
> +    cat "$spdx_file"
Thanks, forgot to remove it.

2023-03-20 08:36 UTC, sven-dmlr approved these changes
It works now. Thank you.

A very good idea to download the checksum :+1:

2023-03-20 08:49 UTC, merged

2023-03-22 08:40 UTC, Jeeppler commented
@sven-dmlr thanks for merging it.