Feature 2040 user defined labels in config
mercedes-benz/sechub pull request #2124
Opened 2023-03-28 15:51 UTC by de-jcup

This PR
- closes #2040
- closes #2125
- closes #2129

2023-03-29 20:05 UTC, Jeeppler requested changes
Overall looks good. However, I found a number of small issues. Please fix those.

In addition, please verify whether your pull-request fixes this issue as well: https://github.com/mercedes-benz/sechub/issues/2071. If it does, please add it to the description.

2023-03-30 11:05 UTC, de-jcup commented on sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidatorTest.java
> +    @ValueSource(strings = { "$variable1", "!something", "<html>", "label:with:colon" })
While adding your suggestions, I ound here a problem in SimpleStringUtils implementation when using umlauts.
Created another issue: 
- #2129

2023-03-30 11:05 UTC, de-jcup commented on sechub-commons-model/src/test/java/com/mercedesbenz/sechub/commons/model/SecHubConfigurationModelValidatorTest.java
> +    @ValueSource(strings = { "$variable1", "!something", "<html>", "label:with:colon" })
Will fix this inside the PR as well.

2023-03-30 12:57 UTC, de-jcup commented on sechub-scan/src/main/resources/templates/report/html/scanresult.html
> +                                <td>:</td>
I need this to identify the parts inside the tests. So I will keep it as is.

2023-03-30 15:32 UTC, de-jcup commented on sechub-scan/src/main/resources/templates/report/html/scanresult.html
> +                                <td>:</td>
Clarified - we are talking about : here and not about the class :-)

2023-03-30 16:35 UTC, Jeeppler approved these changes
Looks good 👍

2023-03-30 16:44 UTC, merged