Feature 2594 fix and enhance systemtest framework
mercedes-benz/sechub pull request #2597
Opened 2023-10-13 15:01 UTC by de-jcup

This PR
- closes #2596 
- closes #2594 
- closes #2593 
- closes #2497
- closes #2605

2023-10-16 07:14 UTC, Jeeppler requested changes
See comments.

2023-10-16 07:14 UTC, Jeeppler commented on sechub-systemtest/src/test/java/com/mercedesbenz/sechub/systemtest/runtime/testengine/SystemTestRuntimeTestEngineTest.java
> +        assertEquals("Was not able to launch SecHub job. Reason: no job createable", currentTestResult.getFailure().getMessage());
```suggestion
        assertEquals("Was not able to launch SecHub job. Reason: unable to create job", currentTestResult.getFailure().getMessage());
```

2023-10-23 16:05 UTC, Jeeppler requested changes
Found some small issues.

2023-10-23 19:43 UTC, Jeeppler requested changes
Please fix the issues from my previous review.

2023-10-24 07:39 UTC, de-jcup commented on sechub-pds-tools/src/test/java/com/mercedesbenz/sechub/pds/tools/PDSToolsCLITest.java
> +                "--sechub-solution-rootfolder", "/path/to/sechub-solution", "--run-tests", "test1,test2" });
I used the standard behavior of JCommander. Means you have few ways to define listes from commandline - please look at https://www.baeldung.com/jcommander-parsing-command-line-parameters#basic-types-1. 

Inside the pds tools client, the help says:

"The (comma separated) name(s) of the tests to run. When defined, only those tests are run. When nothing defined, all system tests are executed"

means: Either the name or a list of names - comma separated

2023-10-24 08:30 UTC, merged

2023-10-24 13:18 UTC, Jeeppler reviewed
Good job.