Feature 1139 rename parts with email adress
mercedes-benz/sechub pull request #2781
Opened 2023-12-22 15:00 UTC by zigfridus

This PR will close #1139

2023-12-28 09:58 UTC, Jeeppler requested changes
Looks good 👍 . I found two minor issues, please fix those.

2023-12-28 09:58 UTC, Jeeppler commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/messaging/UserMessage.java
> +     * shall contain the new mail address in this case.
```suggestion
     * shall contain the new email address in this case.
```

2023-12-28 09:58 UTC, Jeeppler commented on sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/user/UserCreationService.java
> +            LOG.warn("Self registration coming in for user:{} but mailaddress {} already exists. So just removing self registration entry", sanitizedLogUserId,
```suggestion
            LOG.warn("Self registration coming in for user:{} but email address {} already exists. So just removing self registration entry", sanitizedLogUserId,
```

2023-12-29 14:50 UTC, zigfridus commented on sechub-shared-kernel/src/main/java/com/mercedesbenz/sechub/sharedkernel/messaging/UserMessage.java
> +     * shall contain the new mail address in this case.
Done.

2023-12-29 14:51 UTC, zigfridus commented on sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/user/UserCreationService.java
> +            LOG.warn("Self registration coming in for user:{} but mailaddress {} already exists. So just removing self registration entry", sanitizedLogUserId,
Done.

2024-01-02 13:21 UTC, Jeeppler commented
Please request a re-review or let me know once I should look over the pull-request again.

2024-01-02 13:28 UTC, zigfridus commented
@Jeeppler 
I will let you know as soon as I complete this issue.

2024-01-04 10:02 UTC, Jeeppler requested changes
See comments.

2024-01-04 10:02 UTC, Jeeppler commented on sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/validation/UserInputAssertionTest.java
> +        String validMailAddress = "mymail@example.com";
```suggestion
        String validEmailAddress = "mymail@example.com";
```

2024-01-04 10:28 UTC, zigfridus commented on sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/UserAdministrationRestControllerRestDocTest.java
> +        	                                    fieldWithPath(UserDetailInformation.PROPERTY_EMAIL).description("The mail address of the user"),
Done.

2024-01-04 10:29 UTC, zigfridus commented on sechub-administration/src/test/java/com/mercedesbenz/sechub/domain/administration/user/UserEmailAddressUpdateServiceTest.java
> +    void throws_not_acceptable_when_same_mail_address_as_before() {
Done

2024-01-04 10:29 UTC, zigfridus commented on sechub-doc/src/test/java/com/mercedesbenz/sechub/restdoc/AnonymousUserRequestsNewApiTokenRestDocTest.java
> +        		post(apiEndpoint,"emailAddress@test.com").
Done.

2024-01-04 10:40 UTC, zigfridus commented on sechub-integrationtest/src/test/java/com/mercedesbenz/sechub/integrationtest/scenario2/UserRequestsNewAPITokenIntTest.java
> +    public void an_anonymous_user_can_trigger_new_api_token_request_for_existing_user_email_address_leads_to_mail_with_link_to_fetch_new_apitoken() {
Done.

2024-01-04 10:42 UTC, zigfridus commented on sechub-notification/src/main/java/com/mercedesbenz/sechub/domain/notification/NotificationConfiguration.java
> +    @MustBeDocumented(value = "Single mail address used for emails to administrators. This should an NPM (non personalized mailbox)")
Done.

2024-01-04 10:42 UTC, zigfridus commented on sechub-notification/src/test/java/com/mercedesbenz/sechub/domain/notification/user/UserEmailAddressChangedNotificationServiceTest.java
> +        userMessage.setSubject("Your mail address has changed by a test");
Done.

2024-01-04 10:43 UTC, zigfridus commented on sechub-notification/src/test/java/com/mercedesbenz/sechub/domain/notification/user/UserEmailAddressChangedNotificationServiceTest.java
> +        assertEquals("Your mail address has changed by a test and it will not be used any longer for SecHub.\n"
Done.

2024-01-04 10:44 UTC, zigfridus commented on sechub-notification/src/test/java/com/mercedesbenz/sechub/domain/notification/user/UserEmailAddressChangedNotificationServiceTest.java
> +        assertEquals("Your mail address has changed by a test from former_email.address@example.org to email.address@example.org. \n"
Done.

2024-01-04 10:47 UTC, zigfridus commented on sechub-shared-kernel/src/test/java/com/mercedesbenz/sechub/sharedkernel/validation/UserInputAssertionTest.java
> +        String validMailAddress = "mymail@example.com";
Done.

2024-01-04 11:24 UTC, zigfridus commented
@Jeeppler 
I fixed typos from your comments. Please have a look.

2024-01-04 13:17 UTC, Jeeppler approved these changes
Looks good. Thanks for your contribution 🥇

2024-01-04 13:22 UTC, Jeeppler commented
@zigfridus can you fix the merge request? Simply merge the community branch into your branch and overwrite the file (merge it). Since the `reduced-openapi3.json` is auto generated, it does not matter if you use the upstream version or your version. It is only important, that this file exists.

2024-01-04 18:37 UTC, zigfridus commented
@Jeeppler 
My branch had been created before `community` branch and was  connect to the `develop` branch. Could you please advise how to correctly merge it in my case? Thanks
![image](https://github.com/mercedes-benz/sechub/assets/4904593/26a310f6-ef6b-43dd-a80c-8d9eb2cf7cf7)

2024-01-05 09:49 UTC, Jeeppler commented
@zigfridus give the following a try:

1. Checkout the `community` branch
2. Take the `sechub-api-java/src/main/resources/reduced-openapi3.json` JSON and copy it to any folder outside of the sechub git repository
3. Switch to your branch to `feature-1139-rename-parts-with-emailAdress` 
4. copy & replace the `sechub-api-java/src/main/resources/reduced-openapi3.json` with the file on your branch
5. Push the changes (important: don't build your branch)

If the `sechub-api-java/src/main/resources/reduced-openapi3.json` file is identical on the community branch and your branch the merge conflict should be resolved. 

NOTE: Don't build your branch again. Otherwise the `reduced-openapi3.json` will be generated again.

2024-01-05 10:55 UTC, zigfridus commented
@Jeeppler 
Finally no conflicts. Thank you for the advice!

2024-01-05 11:24 UTC, merged