PDS prepare upload remote data to shared storage
mercedes-benz/sechub pull request #3131
Opened 2024-05-15 08:28 UTC by lorriborri

- closes: #3026

2024-05-23 09:00 UTC, de-jcup requested changes
Good job. but there a things to change/discuss.

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/upload/PrepareWrapperUploadService.java
> +            throw new IllegalArgumentException("SecHubConfigurationModel data is not configured.");
```suggestion
            throw new IllegalStateException("SecHubConfigurationModel data is not configured.");
```

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/upload/PrepareWrapperUploadService.java
> +        if (!model.getData().get().getSources().isEmpty()) {
```suggestion
        var data = model.getData().get();
        if (!data.getSources().isEmpty()) {
```
and use below..

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/upload/PrepareWrapperUploadService.java
> +            File file = new File(context.getEnvironment().getPdsPrepareUploadFolderDirectory() + "/sourcecode.zip");
Please use the constants for "sourcecode.zip" and for "binaries.tar"

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/test/java/com/mercedesbenz/sechub/wrapper/prepare/modules/PrepareWrapperModuleGitTest.java
> +    void beforeEach() throws IOException {
For tests it is absolutely okay to always throw any kind of exception. I would do always this:
```suggestion
    void beforeEach() throws Exception {
```

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/test/java/com/mercedesbenz/sechub/wrapper/prepare/modules/PrepareWrapperModuleGitTest.java
> +    String subfolder = "subfolder";
What about: 
```suggestion
    String gitRepositoryName = "git-repository-name";
```

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/test/java/com/mercedesbenz/sechub/wrapper/prepare/upload/FileNameSupportTest.java
> +    FileNameSupport fileNameSupportToTest;
```suggestion
   private FileNameSupport fileNameSupportToTest;
```

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/test/java/com/mercedesbenz/sechub/wrapper/prepare/upload/FileNameSupportTest.java
> +    TestFileWriter writer;
```suggestion
    private TestFileWriter writer;
```

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/upload/PrepareWrapperSharedVolumePropertiesSetup.java
> +    @PDSMustBeDocumented(value = "Defines the root path for shared volume uploads - e.g. for sourcecode.zip etc. When using keyword *temp* as path, this will create a temporary directory (for testing
drop must be documented -works not here

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/upload/PrepareWrapperSharedVolumePropertiesSetup.java
> +    @Value("${pds.storage.sharedvolume.upload.dir:" + UNDEFINED_UPLOAD_DIR + "}") // we use undefined here. Will be used in #isValid()
change to prepare.storage...

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/upload/PrepareWrapperS3PropertiesSetup.java
> +    @Value("${pds.storage.s3.secretkey:" + UNDEFINED + "}") // we use undefined here. Will be used in isValid
### Get integration tests running
The jenkins integration tests use S3 setup.

We have to change 
`continous-integration-multibranch-pipeline.jenkins`

```
// we setup PDS storage with same s3 bucket data
                        PDS_STORAGE_S3_ACCESSKEY = getStringCredentialsOrUndefined('sechub-storage-s3-accesskey')
                        PDS_STORAGE_S3_SECRETKEY = getStringCredentialsOrUndefined('sechub-storage-s3-secretkey')
                        PDS_STORAGE_S3_BUCKETNAME = getStringCredentialsOrUndefined('sechub-storage-s3-bucketname')
                        PDS_STORAGE_S3_ENDPOINT = getStringCredentialsOrUndefined('sechub-storage-s3-endpoint')

// we setup Prepare storage with same s3 bucket data
                        PREPARE_STORAGE_S3_ACCESSKEY = getStringCredentialsOrUndefined('sechub-storage-s3-accesskey')
                        PREPARE_STORAGE_S3_SECRETKEY = getStringCredentialsOrUndefined('sechub-storage-s3-secretkey')
                        PREPARE_STORAGE_S3_BUCKETNAME = getStringCredentialsOrUndefined('sechub-storage-s3-bucketname')
                        PREPARE_STORAGE_S3_ENDPOINT = getStringCredentialsOrUndefined('sechub-storage-s3-endpoint')


```

2024-05-23 09:00 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/upload/PrepareWrapperS3PropertiesSetup.java
> +    @Value("${pds.storage.s3.secretkey:" + UNDEFINED + "}") // we use undefined here. Will be used in isValid
We have to implement this at github actions as well

2024-05-29 12:05 UTC, winzj requested changes
Looking good, well done 👍 

I just found some smaller parts, please have a look at my comments.

2024-05-31 09:13 UTC, lorriborri commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/modules/AbstractInputValidator.java
> +    public PDSLogSanitizer pdsLogSanitizer;
can't because in abstract class -> can not be mocked in tests otherwise

2024-06-12 08:08 UTC, winzj requested changes
Looking good 👍 

I just had some things that are not clear to me.

2024-06-12 09:40 UTC, de-jcup commented on sechub-wrapper-prepare/src/main/java/com/mercedesbenz/sechub/wrapper/prepare/modules/AbstractInputValidator.java
> +    public PDSLogSanitizer pdsLogSanitizer;
Done by me at refactoring phase.

2024-06-12 10:34 UTC, de-jcup commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionEnvironmentPrepare.java
> +public class PDSExecutionEnvironmentPrepare {
You are so right! I did not see this - with #3142 this was handled already in a better way. But I would have to add `PDS_SCRIPT_ENV_WHITELIST=PDS_STORAGE_*` in deployment.yaml her now.
After thinking about the situation (we need always the PDS_SCRIPT_ENV_WHITELIST entry for any kind: local, local integration tests, build env setup (jenkins, github action) , k83s deployments etc.) it makes not so much sense and I created #3220 and will add this implementation inside the PR.

2024-06-13 07:50 UTC, de-jcup commented on sechub-pds/src/main/java/com/mercedesbenz/sechub/pds/execution/PDSExecutionEnvironmentPrepare.java
> +public class PDSExecutionEnvironmentPrepare {
Now #3220 is merged. I will remove the class completely.

2024-06-13 14:28 UTC, de-jcup approved these changes

2024-06-13 14:32 UTC, merged