Feature 3141 implement first version of secret validator application
mercedes-benz/sechub pull request #3280
Opened 2024-07-08 12:10 UTC by winzj

- closes #3141 
- closes #3276

2024-07-15 15:11 UTC, de-jcup requested changes
Good work, but I found some things to discuss.

Additionally: Even when we have no pds solution currently for the validation, we still could write an an integration test by enhancing existing secrect scan integration test (which just returns a sarif result) and call here the wrapper application from build folder (when a variant is set). So we could check this works together with SecHub at all.

2024-07-15 15:11 UTC, de-jcup commented on sechub-wrapper-secret-validator/src/test/java/com/mercedesbenz/sechub/wrapper/secret/validator/cli/SecretValidatorSpringBootTest.java
> +            Location location = finding.getLocations().get(0);
Hmm... at the first glance I was a little bit confused - it took some seconds to understand, that really each finding shall have the same severity in this test cases and that really each finding must have no validation

What about introducing some assert methods here ?

e.g.
```
for (Result finding : run.getResults()) {
    assertFindingHasSecHubSeverity("medium");
    assertFindingIsNotValidated();
}
```
Also you could think about having 2 tests here and separate the assertions...

2024-07-15 15:11 UTC, de-jcup commented on sechub-wrapper-secret-validator/src/test/java/com/mercedesbenz/sechub/wrapper/secret/validator/execution/SecretValidatorExecutionContextFactoryTest.java
> +        SecretValidatorPDSJobResult secretValidatorPDSJobResult = new SecretValidatorPDSJobResult();
Just a hint: You could mock the SecretValidatorPDSJobResult - here you test another implementation as well...

Also the SecretValidatorPDSJobResult could be set inside a field in a `@BeforeEach` method  would reduce boilerplate code

2024-07-15 15:11 UTC, de-jcup commented on sechub-wrapper-secret-validator/src/test/java/com/mercedesbenz/sechub/wrapper/secret/validator/model/SecretValidatorConfigurationModelListTest.java
> +    void test() {
```suggestion
    void json_converter_can_handle_model_in_expected_way() {
```

2024-07-17 12:27 UTC, winzj commented on sechub-wrapper-secret-validator/src/main/java/com/mercedesbenz/sechub/wrapper/secret/validator/model/SecretValidatorConfigurationModelList.java
> +    public List<SecretValidatorConfigurationModel> getValidatorConfigList() {
As far as I know jackson uses the setter if available. Only if no setter is implemented, the getter is used.

2024-08-05 09:48 UTC, de-jcup requested changes
Looks good to me - found only some minor parts which should be changed.

2024-08-05 14:56 UTC, de-jcup approved these changes
Well done - looks good to me :+1:

2024-08-05 15:19 UTC, merged