Provide templates and assets
mercedes-benz/sechub pull request #3545
Opened 2024-10-22 10:40 UTC by de-jcup

This PR

- [x] closes #3520
- [x] closes #3522
- [x] closes #3553
- [x] closes #3523
- [x] closes #3524
- [x] closes #3525
- [x] closes #3705

2024-12-03 09:07 UTC, winzj requested changes
Looks very good, I just found some small parts to change.

Please let me know if I made any false assumptions in my propositions somewhere.

2024-12-03 11:18 UTC, de-jcup commented on sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/project/ProjectTemplateService.java
> +        DomainMessage message = new DomainMessage(MessageID.REQUEST_ASSIGN_TEMPLATE_TO_PROJECT);
As descussed, this service lacks also tests - currently only tested by integration tests -  will add this if it is not too complicated.

2024-12-03 11:18 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/snippet/pds-param-template-metadata-syntax.json
> +        "tempplateType": "WEBSCAN_LOGIN", //<3>
Will add a unit test as well for the pds parameter -> so examples are correct...

2024-12-03 11:22 UTC, de-jcup commented on sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/template/TemplateRestController.java
> +    @RequestMapping(path = "/template/{templateId}", method = RequestMethod.POST)
You are absolutely right:

https://www.baeldung.com/rest-http-put-vs-post

> Conversely, the PUT method should be used to request that the server store the enclosed entity under the provided Request-URI. If the Request-URI points to an existing resource on the server, the supplied entity will be considered a modified version of the existing resource. Therefore, the PUT method call will either create a new resource or update an existing one

will change it

2024-12-03 11:24 UTC, de-jcup commented on sechub-scan/src/main/java/com/mercedesbenz/sechub/domain/scan/asset/AssetService.java
> +            @Autowired AssetFileRepository repository,
Yes, having only one constructor, spring should handle this without annotation at all.

2024-12-03 11:34 UTC, de-jcup commented on sechub-scan/src/test/java/com/mercedesbenz/sechub/domain/scan/asset/AssetFileInformationTest.java
> +        info2.setFileName("filename1");
hm.. maybe the test does also not check this correctly.

2024-12-03 12:27 UTC, de-jcup commented on sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/AdministrationAPIConstants.java
> +    public static final String API_UNASSIGN_TEMPLATE_FROM_PROJECT = API_ADMINISTRATION + "project/{projectId}/template/{templateId}";
We did the same for 
- API_SHOW_PROJECT_DETAILS
- API_CHANGE_PROJECT_DETAILS
- API_DELETE_PROJECT
- ... more

For readability/clearness I would keep it as is.

2024-12-03 12:29 UTC, de-jcup commented on sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/project/ProjectDetailInformation.java
> +    private List<String> templates = new ArrayList<>();
Yes I will change this. But inside Project.java we had also "templates". I will change it there as well to "templateIds"

2024-12-03 12:39 UTC, de-jcup commented on sechub-administration/src/main/java/com/mercedesbenz/sechub/domain/administration/project/ProjectDetailInformation.java
> +    private List<String> templates = new ArrayList<>();
Will change this. Will also change Project.java (an entity) + column names + flyway parts

2024-12-05 06:51 UTC, de-jcup commented on sechub-openapi-java/src/main/resources/openapi.yaml
> +    post:
This is not the template change mechanism mentioned before.

I will keep this is as - reason: we use POST for every upload mechanism inside SecHub and PDS.

2024-12-06 05:54 UTC, merged