Feature 607 provide pds zap integration
mercedes-benz/sechub pull request #876
Opened 2021-11-05 19:06 UTC by Jeeppler

OWASP ZAP + PDS:

- Helm chart
- Docker container
- Documentation

2022-04-07 09:38 UTC, winzj requested changes
Please see my comments.

2022-04-08 05:06 UTC, winzj approved these changes
Looks good to me.

2022-04-08 09:22 UTC, sven-dmlr requested changes
Please see comments.

Looking forward to see PDS with OWASP-Zap running. :-)

2022-04-08 09:22 UTC, sven-dmlr commented on sechub-pds-solutions/owasp-zap/docker-compose_pds_owasp_zap_cluster.yaml
> +      name: "sechub"
pls fix identation:
```suggestion
        name: "sechub"
```

2022-04-08 09:22 UTC, sven-dmlr commented on sechub-pds-solutions/owasp-zap/helm/pds-owasp-zap/templates/deployment.yaml
> +                    - containerPort: 8444
Please add startup+liveness probes:
```suggestion
                    - name: pds-https-port
                      containerPort: 8444
                  startupProbe:
                    httpGet:
                      scheme: HTTPS
                      path: /api/anonymous/check/alive
                      port: pds-https-port
                    periodSeconds: 1
                    failureThreshold: 300
                    # probe every 1s x 300 = 5 mins before restart of container
                    successThreshold: 1
                    timeoutSeconds: 1
                  livenessProbe:
                    httpGet:
                      scheme: HTTPS
                      path: /api/anonymous/check/alive
                      port: pds-https-port
                    periodSeconds: 5
                    failureThreshold: 3
                    successThreshold: 1
                    timeoutSeconds: 3
```

2022-04-08 14:59 UTC, Jeeppler commented on sechub-pds-solutions/owasp-zap/10-create-ubuntu-image.sh
> +docker build --pull --no-cache --build-arg BASE_IMAGE=$BASE_IMAGE --tag "$REGISTRY:$VERSION" --file docker/Owasp-Zap-Ubuntu.dockerfile docker/
A tag is just a label which can move, just like the special label `latest`.

For example, Ubuntu 20.04 was released in April of 2020. However, at the time of writing, the latest Ubuntu 20.04 image is tagged with: [20.04, focal-20220404, focal, latest](https://hub.docker.com/_/ubuntu/). The Ubuntu `focal-20220404` tag shows the image was build on the 4th of April 2022. Meaning, the tag `20.04` points to an image which was build two years after the official release.

As a result, I don't think it is a good idea to change the behavior of the script based on the tags.

Furthermore, the problem which you are referring too is specific to organizations which do not have a DockerHub subscription or surpassed their limits.

> Then this error may occur: "toomanyrequests: You have reached your pull rate limit."

There are a number of solutions on how to fix the `toomanyrequests` issue, without changing the behavior of this script.

2022-04-11 07:33 UTC, sven-dmlr approved these changes

2022-04-11 12:14 UTC, merged